---
title: "fitting-exercise"
author: "Murphy John"
format: html
editor: visual
---

# Setup

```{r}
# load packages
library(ggplot2)
library(dplyr)
```

```{r}
# load data
dat <- read.csv(
  here::here("fitting-exercise/data/Mavoglurant_A2121_nmpk.csv")
  )

names(dat) <- tolower(names(dat))
```

# Initial EDA

```{r, fig.width=10, fig.height=5}
# plot time by dv for each id, stratified by dose
plot <- ggplot(dat) +
  geom_line(aes(x=time, y=dv, group=id)) +
  facet_wrap(~dose)

print(plot)
```

# Initial processing

```{r}
# keep only obs where occ=1
dat1 <- dat %>%
  filter(occ == 1)
```

```{r}
# exclude obs where time=0, sum dv for each id
dat2 <- dat1 %>%
  filter(time != 0) %>%
  group_by(id) %>%
  summarize(
    Y = sum(dv)
  )

# create df with time=0 obs only
dat3 <- dat1 %>%
  filter(time == 0)

# join by id
dat4 <- full_join(x=dat2, y=dat3, by="id")
```

```{r}
# convert race and sex to factors
# keep only Y, dose, age, sex, race, wt, ht
dat5 <- dat4 %>%
  mutate(
    race = factor(race),
    sex = factor(sex)
  ) %>%
  select(
    Y, dose, age, sex, race, wt, ht
  )

str(dat5)
```

# EDA

```{r}
# participant demographics by dose
table1 <- dat5 %>%
  gtsummary::tbl_summary(
    include = c(age, sex, race, wt, ht),
    by = dose
  ) %>%
  gtsummary::as_kable()

print(table1)
```

```{r, fig.width=3, fig.height=3}
# plot Y by dose
plot1 <- ggplot(dat5) +
  geom_boxplot(aes(x=factor(dose), y=Y))

print(plot1)

# plot Y by age
plot2 <- ggplot(dat5) +
  geom_point(aes(x=age, y=Y))

print(plot2)

# plot Y by sex
plot3 <- ggplot(dat5) +
  geom_boxplot(aes(x=sex, y=Y))

print(plot3)
```

```{r, fig.width=3, fig.height=3}
# distribution of Y
hist1 <- ggplot(dat5) +
  geom_histogram(aes(Y))

print(hist1)

# distribution of dose
bar1 <- ggplot(dat5) +
  geom_bar(aes(dose))

print(bar1)

# distribution of age
hist2 <- ggplot(dat5) +
  geom_histogram(aes(age))

print(hist2)

# distribution of sex
bar2 <- ggplot(dat5) +
  geom_bar(aes(sex))

print(bar2)

# distribution of race
bar3 <- ggplot(dat5) +
  geom_bar(aes(race))

print(bar3)

# distribution of wt
hist3 <- ggplot(dat5) +
  geom_histogram(aes(wt))

print(hist3)

# distribution of ht
hist4 <- ggplot(dat5) +
  geom_histogram(aes(ht))

print(hist4)
```

```{r, fig.height=10, fig.width=10}
# pair plot
pairs(dat5)
```

# General wrangling and EDA comments




